### ISSUE TITLE
Post Gigs form: add date format enforcement and validation

### ISSUE THREAD

**Issue by esteban-gs** [gig-central/gig-repo-1#209]
### Capture date in correct format and enforce validation
As an employer posting Gigs
I want the Gig Posting End date to be correct
So that my Gig has the correct information

### Approach
- Find a date picker, or some way to enforce date capture in the correct format - yyyy-mm-dd and implement where the date is captured on the Post Gig page
- An alternative might be to post the correct format with the field, have effective date validation and provide messaging to the user when the date is not the correct format

### Tasks:
- [ ] Research and determine the best way to control date input
- [ ] Present approach and get buy-in from team mates
- [ ] Outline additional tasks for implementation & do it!

### Historical information:

###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
**Bug**
###_Severity (1-4; 1 - not severe, 4 - very severe):
 **4**
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
**4**
###_Synopsis - describe bug/task/future request, in more detail: 
Date format is not enforced. Any string is accepted
![20190530_165042](https://user-images.githubusercontent.com/26440947/58672317-4060d200-82fb-11e9-8f16-e92f4f7ca47a.gif)
###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
**Preferably a datepicker. Also datetime has to be written in SQL syntax**

###_Actual Behavior - what the behavior is instead, for bugs only: 
Any strin is accepted
###_Steps to Repro the Issue, for bugs only:
**gig/add
post gigs
Fill out the form
Pull the closeout date in your DB, you will see the string as written on form**

###_Other Notes, for bug/task/future requests:

**Comment by esteban-gs** [comment]
Hi @tranzilla, are you currently working on this issue?

**Comment by thomaskise** [comment]
date validation was removed from #224 and is now just in this task.

See [Stack overflow](https://stackoverflow.com/questions/14359158/codeigniter-date-format-form-validation) for possible solution
