### ISSUE TITLE
Create a Job Category search filter

### ISSUE THREAD

**Issue by james-shively-iii** [gig-central/gig-repo-1#234]
### Create a search filter that is adequate and concise for the user.
As a student looking for Gigs
I need to know the job category
So that I can identify jobs within my area of interest

**Approach:**
- Create anew job category field for filter instead of job description (see Post page)
- Hide filters if less that _X_ number of jobs. _X_ is a constant that is probably inside the config file. 
- Consider addition of Job Title also. A Job Category could have 0, 1 or more Job Titles (not part of tis story)

**Tasks:**
- [ ] Model Job Category field and get consensus before implementation
Consider:
- A Gig will have one and only one Job Category and a Job Category will have 0, 1 or many Gigs
- A Job Title (future data element) will have one and only one Job Category and a Job Category will have 0, 1, or many Gigs
- Is it a separate table, or an attribute of Gigs?
- [ ] Create Job Category field in the database
- [ ] Add Job Category field to the "Add post" page
- [ ] Create Job Category filter
- Probably just an adaptation of existing Job Description filter
- [ ] On the Find a Gig page, replace the Job Description Filter with the Job Category filter

**Comment by james-shively-iii** [comment]
I assigned this task to Esmeralda but she has not accepted the invitation for collaboration.  She will be added soon.
