### ISSUE TITLE
TEST - Venues View #172

### ISSUE THREAD

**Issue by aliyacodes** [gig-central/gig-repo-1#281]
As a user, I need to know that I can find and post a venue, before logging in or joining.
- [ ] #172 Uncomment out links on main page
- [ ] #172 Reimplement views/venues into application  
- [ ] #172 Test corresponding database information accordingly
